### ISSUE TITLE
Token scope

### ISSUE THREAD

**Issue by mastef** [kolpav/purge-artifacts-action#7]
What is the required GITHUB_TOKEN scope? Maybe worth adding to the readme that it can be generated in https://github.com/settings/tokens

**Comment by IanVaughan** [comment]
I don't think scopes need to be set, and they are not configurable for `GITHUB_TOKEN` in any case.
They are predefined here https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token
